name:         seele-frontend
version:      0.1.0
author:       zypeh
maintainer:   zypeh.geek@gmail.com
github:       zypeh/Seele

executables:
  seele-frontend:
    source-dirs:  src
    main:         Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - http-client
    - http-types
    - seele-lib
    - wai
    - warp
    - http-reverse-proxy